# === SmartPicture Backend Cloud Run 配置 ===
runtime: python
env: flex

entrypoint: gunicorn --bind :$PORT app:app

# === 环境变量 ===
env_variables:
  FLASK_ENV: "production"
  GOOGLE_API_KEY: "AIzaSyDnxJ78LLnPx4d05xcbax0FD9p-6Dx3xKg"
  GOOGLE_CLOUD_PROJECT: "alert-autumn-467806-j3"
  GCP_LOCATION: "us-central1"
  PYTHONPATH: "/app"

# === 网络与端口 ===
service: smartpicture-backend
runtime_config:
  python_version: 3.9

# === Cloud Run 服务配置 ===
# 最多同时处理的请求数
instance_class: F2
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.7

# === 日志与健康检查 ===
readiness_check:
  path: "/"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 1

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 5
  success_threshold: 1

# === 权限设置 ===
# 允许公共访问（如果你希望开放 API）
# handlers:
#   - url: /.*
#    script: auto
#    secure: always
#    redirect_http_response_code: 301
